### ISSUE TITLE
Shorcuts conflict with the shell

### ISSUE THREAD

**Issue by liondandelion** [lupantano/readingstrip#11]
Hi,

extension settings display only a single `Super+Ctrl+Space` shortcut to toggle it on/off, but it actually has 4 different shortcuts: `(Shift)+Super+Ctrl+Space` and `(Shift)+Super+Space`, but `(Shift)+Super+Space` is used to change keyboard layout in the shell by default, which doesn't work with the extension enabled. 

I guess they can just be removed? I will send a PR shortly anyway :p

**Comment by lupantano** [comment]
You are right, I will remove the shortcut Super+space.
ty mate
ps.
I will add new shortcut "hotkey-vertical" in the next release but today it's not active in the code.
