### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by idoric** [lupantano/readingstrip#17]
GNOME Shell moved from GJS’ own custom imports system to standard JavaScript modules (ESM). That breaking change require a separate release for 45 and <=44.

https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

**Comment by sobkas** [comment]
Have a partial port to Gnome 45, https://github.com/sobkas/readingstrip
Couldn't port preferences yet.

**Comment by idoric** [comment]
I just installed it. At least now I can use it under GNOME 45. Thank you for taking care of this extension.

**Comment by sanjayankur31** [comment]
> Have a partial port to Gnome 45, https://github.com/sobkas/readingstrip Couldn't port preferences yet.

Is it worth opening a WIP PR here so the maintainer (and others) can chime in (and maybe help complete it?)?

**Comment by petar-v** [comment]
This is solved here: https://github.com/lupantano/readingstrip/pull/19/files 

Please do test it, folks :) 

@sobkas Thanks for porting the extension. I ported it with prefs. Wish I had seen this issue first since you've done lots of work. Please review my PR if you can.

**Comment by idoric** [comment]
@petar-v I just tested it quickly, everything seems to work. Well done and thank you. The only improvement I could see is to replace the "show/hide" with a switch.

**Comment by petar-v** [comment]
@idoric Thanks so much!

New functionality is beyond the scope of this but I am happy to do that in another PR at some point in time. Otherwise, if you have that implemented, I'll cherry-pick it from you :) 

Glad it works, though.

**Comment by kbdragon** [comment]
@petar-v 
Could I have a clue how to install your updated version? I'm on G46 and need the extension badly

**Comment by idoric** [comment]
@kbdragon Extract [readingstrip@lupantano.gihthub.zip](https://github.com/user-attachments/files/15753035/readingstrip%40lupantano.gihthub.zip) in ~/.local/share/gnome-shell/extensions. You will certainly have to exit and restart your session before you can activate it, for example with [Extension Manager](https://flathub.org/apps/com.mattjakeman.ExtensionManager).

**Comment by kbdragon** [comment]
@idoric 
Thank you!

**Comment by lupantano** [comment]
I merged your code with the latest version of readingstrip.
It is definitely buggy, try it.

**Comment by idoric** [comment]
It's not my code, it's @petar-v's (see https://github.com/lupantano/readingstrip/issues/17#issuecomment-2001702497). And his version works for me. Maybe the difference is in the [run.sh file](https://github.com/lupantano/readingstrip/pull/19/files)?

**Comment by lupantano** [comment]
now it works on gnome 45 and 46

**Comment by petar-v** [comment]
Thanks everyone! Just upgraded and works perfectly!
