### ISSUE TITLE
Feature request: Add vertical reading strip as alternative.

### ISSUE THREAD

**Issue by knbknb** [lupantano/readingstrip#4]
**Feature Request**

I would like to suggest a new feature, one that does the same thing as this extension, just in the vertical direction.

This would be really useful for graphic designers who want to check if their margins and indentations (in some website, infographic...) line up properly when displayed on the screen. These people really care about margins.

I would be happy if you  simply included a link in the README.md file. The link could point to someone else's  Gnome Shell Extension, or to some 3rd-party repository....

However, I _really_ like _your_ design, the  transparent yellow strip. That is why I post this here.

Perhaps you can just create a second Gnome Shell Extension "indentationcheck", just like this one? That would be great.

Meanwhile, I'll keep looking for that, maybe there exists something already out there on the net...

(I know I can use the left margin of any app window (e.g. the left margin of an empty browser window) to improvise a guideline/ruler. But that's not so convenient. And it is not transparent.

**Comment by lupantano** [comment]
done 😄 Now we have a vertical strip
