### ISSUE TITLE
Add PO language and other preferences.

### ISSUE THREAD

**Issue by albanobattistella** [lupantano/readingstrip#5]
Ciao,

volevo fare i miei complimenti per questa bellissima estensione che aiuta molto i bambini con dislessia e altre patologie.
In alcune scuole viene utilizzato con risultati ottimi su Zorin Os.
Volevo chiederti se possibile una confgurazione delle preferenze dei colori piu' agevola aggiornando la gui.
Inoltre, se possibile inserire un file traduzione.
Grazie,complimenti ancora e a disposizione.
Saluti,
Albano

**Comment by lupantano** [comment]
Buongiorno Albano,
ti ringrazio molto per il feedback. Come richiesto ho inserito la possibilità di scegliere il colore tramite menù dedicato.
Per quanto riguarda il file di traduzione attualmente mi sembra superfluo tenendo conto del numero esiguo di stringe e della loro leggibilità.
A presto
L.

**Comment by albanobattistella** [comment]
Buongiorno,

Grazie mille!
A presto.
A.
________________________________
Da: lupantano ***@***.***>
Inviato: lunedì 11 luglio 2022 07:34
A: lupantano/readingstrip ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [lupantano/readingstrip] Add PO language and other preferences. (Issue #5)


Buongiorno Albano,
ti ringrazio molto per il feedback. Come richiesto ho inserito la possibilità di scegliere il colore tramite menù dedicato.
Per quanto riguarda il file di traduzione attualmente mi sembra superfluo tenendo conto del numero esiguo di stringe e della loro leggibilità.
A presto
L.
