### ISSUE TITLE
No preferences displayed.

### ISSUE THREAD

**Issue by albanobattistella** [lupantano/readingstrip#6]
Ciao,
ho aggiornato l'estensione, ma mentre prima veniva mostrato il display per il meu, ora non mi permette di vederlo.
Noi su Zorin usiamo gnome shell 3.38, ma la versione precedente veniva vista tranquillamente.
Ti ringrazio.
A presto.
Albano
![Schermata da 2022-07-11 09-12-34](https://user-images.githubusercontent.com/34811668/178209062-60f5661f-b366-45c8-b484-cf737735c5c6.png)

**Comment by lupantano** [comment]
Lo screenshot non dice molto. In questo momento sto usando gnome 42, proverò ad emulare gnome 3.x per vedere quale possa essere il problema.

**Comment by albanobattistella** [comment]
> Lo screenshot non dice molto. In questo momento sto usando gnome 42, proverò ad emulare gnome 3.x per vedere quale possa essere il problema.

Grazie!

**Comment by lupantano** [comment]
Ho provato con l'ultima versione di Zorin OS. Il bug sembrerebbe risolto.
Prova ad installare l'estensione tramite git, se tutto dovesse funzionare a dovere aggiungerò la nuova versione su gnome extensions

**Comment by albanobattistella** [comment]
Grazie mille per il tuo lavoro!
Se hai dei commenti/consigli per Zorin siamo qui.
________________________________
Da: lupantano ***@***.***>
Inviato: lunedì 25 luglio 2022 19:30
A: lupantano/readingstrip ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [lupantano/readingstrip] No preferences displayed. (Issue #6)


Ho provato con l'ultima versione di Zorin OS. Il bug sembrerebbe risolto.
Prova ad installare l'estensione tramite git, se tutto dovesse funzionare a dovere aggiungerò la nuova versione su gnome extensions

**Comment by lupantano** [comment]
Passate alla nuova versione di GNOME perché per far funzionare la mia estensione su quella "vecchia" ho dovuto sudare :-D
Sto scherzando.
A presto

**Comment by albanobattistella** [comment]
Grazie!
Noi diamo la LTS  per gli utenti che è più stabile e 5 anni di supporto.
Pe il prossimo anno uscirà Zorin 17 e sicuramente con nuova shell di gnome.
Vorrei che l'installazione dell'estensione sia più semplice possibile anche per i non esperti.
Hai un recapito?
Grazie ancora di tutto.
A.
________________________________
Da: lupantano ***@***.***>
Inviato: lunedì 25 luglio 2022 19:44
A: lupantano/readingstrip ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [lupantano/readingstrip] No preferences displayed. (Issue #6)


Passate alla nuova versione di GNOME perché per far funzionare la mia estensione su quella "vecchia" ho dovuto sudare :-D
Sto scherzando.
A presto

**Comment by lupantano** [comment]
Se vuoi mi trovi su matrix. **@lupantano:matrix.org** 

Comunque l'estensione è presente [gnome extensions](https://extensions.gnome.org/extension/4419/reading-strip/), installarla da lì è molto semplice. La versione github è solamente più aggiornata.

**Comment by albanobattistella** [comment]
Grazie!

ho provato ora...se installo da git, tutto ok..ma e provo da gnome extension mi da lo stesso problema.
Forse non ha ancora caricato la nuova.
Grazie.
________________________________
Da: lupantano ***@***.***>
Inviato: lunedì 25 luglio 2022 20:03
A: lupantano/readingstrip ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [lupantano/readingstrip] No preferences displayed. (Issue #6)


Se vuoi mi trovi su matrix. @lupantano<https://github.com/lupantano>:matrix.org

Comunque l'estensione è presente gnome extensions<https://extensions.gnome.org/extension/4419/reading-strip/>, installarla da lì è molto semplice. La versione github è solamente più aggiornata.

**Comment by lupantano** [comment]
Come ti dicevo la versione su git è sempre la più aggiornata/buggata :-D Mentre su gnome extension tendo a mettere versioni rodate e forse con un pelino meno di bug. 
A presto

p.s. sarei curioso di sapere in quali scuole è usata l'app ed avere un feedback da parte dei DSA che la usano, contattami su matrix non appena puoi.

**Comment by albanobattistella** [comment]
> Come ti dicevo la versione su git è sempre la più aggiornata/buggata :-D Mentre su gnome extension tendo a mettere versioni rodate e forse con un pelino meno di bug. A presto
> 
> p.s. sarei curioso di sapere in quali scuole è usata l'app ed avere un feedback da parte dei DSA che la usano, contattami su matrix non appena puoi.

Ciao,
certamente....ti contatto e ti invio qualcosa. :-)
